import { type NextPage } from "next";
import Head from "next/head";
import { Timeline } from "../../components/Tweets/Timeline";

const Community: NextPage = () => {

  return (
    <>
      <Head>
        <title>Something</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen w-screen flex-col p-4 align-middle lg:container lg:px-16">
        <Timeline where={{}} />
      </main>
    </>
  );
};

export default Community;
