import { type NextPage } from "next";
import Head from "next/head";
import { Container } from "../../components/Tweets/Container";
import { Timeline } from "../../components/Tweets/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Something</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Timeline where={{}} />
      </Container>
    </>
  );
};

export default Home;
